routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function () {
    Route::resource('account', 'AccountController');
    Route::resource('costCenter', 'CostCenterController');
    Route::resource('courseCode', 'CourseCodeController');
    Route::resource('timeSheet', 'TimeSheetController');
    Route::resource('timeRecords', 'TimeRecordController');
    Route::post('/search', 'TimeSheetController@index')->name('search');
});

Route::get('/timeSheet/downloadts/{costCenterid?}/{innovationID?}/{colnnovateid?}/{ktpid?}/{academyid?}/{ptlid?}', 'TimeSheetController@generateTimeSheetsPDF')->name('timeSheet.generateTimeSheetsPDF');
Route::get('/timeSheet/{id}/downloadtimesheet/{costCenterid?}', 'TimeSheetController@generateTimeSheetPDF')->name('timeSheet.generateTimeSheetPDF');
Route::get('/timeSheet/{id}/downloadktp/{costCenterid?}', 'TimeSheetController@generateKtpCCPDF')->name('timeSheet.generateKtpPDF');
Route::get('/timeSheet/{id}/downloadacademy/{costCenterid?}', 'TimeSheetController@generateAcademyPDF')->name('timeSheet.generateAcademyPDF');
Route::get('/timeSheet/{id}/downloadcolnnovate/{costCenterid?}', 'TimeSheetController@generateColnnovatePDF')->name('timeSheet.generateColnnovatePDF');

Route::get('/timeSheet/{id}/downloadptl', 'TimeSheetController@generatePTLPDF')->name('timeSheet.generatePTLPDF');

Route::get('/tests', 'TimeSheetController@andrew')->name('timeSheet.andrew');
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/pdfdwl', 'TimeSheetController@generateTimeSheetsTestPDF')->name('timeSheet.generateTimeSheetsTestPDF');

Route::get('/test', 'VisitsController@getVisitsByMonth')->name('visits.test');

app/CostCenter.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CostCenter extends Model
{
    public function user() {
        return $this->belongsToMany('App\User');
    }

    public function timeRecord() {
        return $this->hasMany('App\TimeRecord');
    }

    protected $fillable = [
        'type', 'number', 'user_id'
    ];
}

app/Http/Controllers/CostCenterController.php
<?php

namespace App\Http\Controllers;

use App\CostCenter;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;

class CostCenterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $costCenter = CostCenter::all();
        return view('CostCenter.index', compact('costCenter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $costCenter = CostCenter::all();
        return view('CostCenter.create', compact('costCenter'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'type' => 'required|string',
            'number' => 'required|integer|min:4',
        ]);

        $costCenter = new CostCenter;
        $costCenter->type = $request->type; 
        $costCenter->number = $request->number;
        $costCenter->save();
        return redirect('/costCenter')->with('Created');
        return response()->json([
            "message" => "costCenter created"
        ], 201);
        /*
      

        $costCenter = CostCenter::firstOrNew([
            'type' => $request->get('type'),
            'number' => $request->get('number'),
            'user_id' => Auth::user()->id,
        ]);
        $costCenter->save();

        return redirect('/costCenter')->with('Created');
        */

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\CostCenter  $costCenter
     * @return \Illuminate\Http\Response
     */
    public function show(CostCenter $costCenter)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\CostCenter  $costCenter
     * @return \Illuminate\Http\Response
     */
    public function edit(CostCenter $costCenter)
    {
        $users = User::all();
        return view('CostCenter.edit', compact('costCenter', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\CostCenter  $costCenter
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, CostCenter $costCenter)
    {
        $request->validate([
            'type' => 'required|string|Max:255',
            'number' => 'required|integer|Min:4',
        ]);
        $costCenter->type = is_null($request->type) ? $costCenter->type : $request->type;
        $costCenter->number = is_null($request->number) ? $costCenter->number : $request->number;
        $costCenter->user_id = is_null($request->user_id) ? $costCenter->user_id : $request->user_id;
        $costCenter->save();
        return redirect('/costCenter');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\CostCenter  $costCenter
     * @return \Illuminate\Http\Response
     */
    public function destroy(CostCenter $costCenter)
    {
        $costCenter->delete();
        return redirect('/costCenter');
    }
}

resources/views/CostCenter/create.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	{{-- Declare Page Size --}}
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Create New Cost Center</h1>
        <div>
        <form method="POST" action="{{route('costCenter.store')}}">
            @csrf
            <div class="form-group">
                <label for="type">type:</label>
                <input type="text" class="form-control" name="type"/>
            </div>

            <div class="form-group">
                <label for="number">Number:</label>
                <input type="number" class="form-control" name="number"/>
            </div>
            <button type="submit" class="btn btn-primary">Create Project</button>
        </form>

		{{-- Error Checking --}}
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/CostCenter/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	{{-- Declare Page Size --}}
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit Cost Center</h1>
        <div>
        <form method="post" action="{{ route('costCenter.update', $costCenter->id)}}">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="type">type:</label>
                <input type="text" class="form-control" name="type" value="{{ $costCenter->type }}">
            </div>
            <div class="form-group">
                <label for="number">Number:</label>
                <input type="number" class="form-control" name="number" value="{{ $costCenter->number }}">
            </div>
            <div class="form-group">
                <label for="users">Users:</label>
                <select name="users">
                @foreach($users as $user)
                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-secondary">Update</button>
        </form>

		{{-- Error Checking --}}
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/CostCenter/index.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	{{-- Declare Page Size --}}
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Cost Center Index</h1>
        <table>
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Number</th>
                </tr>
            </thead>
            <div><a style="margin:19px;" href="{{route('costCenter.create')}}" class="btn btn-primary">New Cost Center</a></div>
            <tbody>
                @foreach ($costCenter as $costCenter)
                    <tr>
                        <td>{{ $costCenter->type }}</td>
                        <td>{{ $costCenter->number  }}</td>
                        <td><a href="{{route('costCenter.edit', $costCenter->id)}}" class="btn btn-primary">Edit</a></td>
                        <td><form action="{{route('costCenter.destroy', $costCenter->id)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-primary" type="sumbit"> Delete</button></form></td>
                    </tr> 
                @endforeach
            </tbody>
        </table>
		{{-- Error Checking --}}
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection