routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function () {
    Route::resource('account', 'AccountController');
    Route::resource('costCenter', 'CostCenterController');
    Route::resource('courseCode', 'CourseCodeController');
    Route::resource('timeSheet', 'TimeSheetController');
    Route::resource('timeRecords', 'TimeRecordController');
    Route::post('/search', 'TimeSheetController@index')->name('search');
});

Route::get('/timeSheet/downloadts/{costCenterid?}/{innovationID?}/{colnnovateid?}/{ktpid?}/{academyid?}/{ptlid?}', 'TimeSheetController@generateTimeSheetsPDF')->name('timeSheet.generateTimeSheetsPDF');
Route::get('/timeSheet/{id}/downloadtimesheet/{costCenterid?}', 'TimeSheetController@generateTimeSheetPDF')->name('timeSheet.generateTimeSheetPDF');
Route::get('/timeSheet/{id}/downloadktp/{costCenterid?}', 'TimeSheetController@generateKtpCCPDF')->name('timeSheet.generateKtpPDF');
Route::get('/timeSheet/{id}/downloadacademy/{costCenterid?}', 'TimeSheetController@generateAcademyPDF')->name('timeSheet.generateAcademyPDF');
Route::get('/timeSheet/{id}/downloadcolnnovate/{costCenterid?}', 'TimeSheetController@generateColnnovatePDF')->name('timeSheet.generateColnnovatePDF');

Route::get('/timeSheet/{id}/downloadptl', 'TimeSheetController@generatePTLPDF')->name('timeSheet.generatePTLPDF');

Route::get('/tests', 'TimeSheetController@andrew')->name('timeSheet.andrew');
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/pdfdwl', 'TimeSheetController@generateTimeSheetsTestPDF')->name('timeSheet.generateTimeSheetsTestPDF');

Route::get('/test', 'VisitsController@getVisitsByMonth')->name('visits.test');

app/CourseCode.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CourseCode extends Model
{
    public function user() {
        return $this->belongsTo('App\User');
    }

    protected $fillable = [
        'name', 'number', 'user_id'
    ];
}

app/Http/Controllers/CourseCodeController.php
<?php

namespace App\Http\Controllers;

use App\CourseCode;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;

class CourseCodeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $courseCodes = CourseCode::all();
        return view('courseCode.index', compact('courseCodes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $courseCode = CourseCode::all();
        return view('courseCode.create', compact('courseCode'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'number' => 'required|integer|min:4',
        ]);

        $courseCode = new CourseCode;
        $courseCode->name = $request->name; 
        $courseCode->number = $request->number; 
        $courseCode->user_id = Auth::user()->id; 
        $courseCode->save();
        return redirect('/courseCode')->with('Created');


        // $courseCode = CourseCode::firstOrNew([
        //     'name' => $request->get('name'),
        //     'user_id' => Auth::user()->id,
        // ]);

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\courseCode  $courseCode
     * @return \Illuminate\Http\Response
     */
    public function show(CourseCode $courseCode)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\courseCode  $courseCode
     * @return \Illuminate\Http\Response
     */
    public function edit(CourseCode $courseCode)
    {
        $users = User::all();
        return view('courseCode.edit', compact('courseCode', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\courseCode  $courseCode
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, CourseCode $courseCode)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'number' => 'required|integer|Min:3',
        ]);
        $courseCode->name = is_null($request->name) ? $courseCode->name : $request->name;
        $courseCode->number = is_null($request->number) ? $courseCode->number : $request->number;
        $courseCode->user_id = is_null($request->user_id) ? $courseCode->user_id : $request->user_id;
        $courseCode->save();
        return redirect('/courseCode');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\courseCode  $courseCode
     * @return \Illuminate\Http\Response
     */
    public function destroy(CourseCode $courseCode)
    {
        $courseCode->delete();
        return redirect('/courseCode');
    }
}

resources/views/courseCode/create.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	{{-- Declare Page Size --}}
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Create Course Code</h1>
        <div>
        <form method="POST" action="{{route('courseCode.store')}}">
            @csrf
            <div class="form-group">
                <label for="number">Name:</label>
                <input type="text" class="form-control" name="name"/>
                <label for="number">Number:</label>
                <input type="number" class="form-control" name="number"/>
            </div>
            <button type="submit" class="btn btn-primary">Create Course</button>
        </form>

        
		{{-- Error Checking --}}
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/courseCode/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	{{-- Declare Page Size --}}
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit Course Code</h1>
        <div>
        <form method="post" action="{{ route('courseCode.update', $courseCode->id)}}">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name" value="{{ $courseCode->name }}">
                <label for="number">Number:</label>
                <input type="number" class="form-control" name="number" value="{{ $courseCode->number }}">
            </div>

            <div class="form-group">
                <label for="users">Users:</label>
                <select name="users">
                @foreach($users as $user)
                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-secondary">Update</button>
        </form>

        
		{{-- Error Checking --}}
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/courseCode/index.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	{{-- Declare Page Size --}}
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Course Codes</h1>
        <div>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number</th>
                </tr>
            </thead>
            <div><a style="margin:19px;" href="{{route('courseCode.create')}}" class="btn btn-primary">New Course</a></div>
            <tbody>
                @foreach ($courseCodes as $courseCode)
                    <tr>
                        <td>{{ $courseCode->name  }}</td>
                        <td>{{ $courseCode->number  }}</td>
                        <td><a href="{{route('courseCode.edit', $courseCode->id)}}" class="btn btn-primary">Edit</a></td>
                        <td><form action="{{route('courseCode.destroy', $courseCode->id)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-primary" type="sumbit"> Delete</button></form></td>
                    </tr> 
                @endforeach
            </tbody>
        </table>


		{{-- Error Checking --}}
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection