routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function () {
    Route::resource('account', 'AccountController');
    Route::resource('costCenter', 'CostCenterController');
    Route::resource('courseCode', 'CourseCodeController');
    Route::resource('timeSheet', 'TimeSheetController');
    Route::resource('timeRecords', 'TimeRecordController');
    Route::post('/search', 'TimeSheetController@index')->name('search');
});

Route::get('/timeSheet/downloadts/{costCenterid?}/{innovationID?}/{colnnovateid?}/{ktpid?}/{academyid?}/{ptlid?}', 'TimeSheetController@generateTimeSheetsPDF')->name('timeSheet.generateTimeSheetsPDF');
Route::get('/timeSheet/{id}/downloadtimesheet/{costCenterid?}', 'TimeSheetController@generateTimeSheetPDF')->name('timeSheet.generateTimeSheetPDF');
Route::get('/timeSheet/{id}/downloadktp/{costCenterid?}', 'TimeSheetController@generateKtpCCPDF')->name('timeSheet.generateKtpPDF');
Route::get('/timeSheet/{id}/downloadacademy/{costCenterid?}', 'TimeSheetController@generateAcademyPDF')->name('timeSheet.generateAcademyPDF');
Route::get('/timeSheet/{id}/downloadcolnnovate/{costCenterid?}', 'TimeSheetController@generateColnnovatePDF')->name('timeSheet.generateColnnovatePDF');

Route::get('/timeSheet/{id}/downloadptl', 'TimeSheetController@generatePTLPDF')->name('timeSheet.generatePTLPDF');

Route::get('/tests', 'TimeSheetController@andrew')->name('timeSheet.andrew');
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/pdfdwl', 'TimeSheetController@generateTimeSheetsTestPDF')->name('timeSheet.generateTimeSheetsTestPDF');

Route::get('/test', 'VisitsController@getVisitsByMonth')->name('visits.test');

app/TimeSheet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;


class TimeSheet extends Model
{
    public function timeRecords() {
        return $this->hasMany('App\TimeRecord');
    }
   
    protected $fillable = [
        'month', 'year', 'user_id', 'name', 'company'
    ];

    /**
     * Get total minutes for grade 3
     *
     * @return minutes total
     */
    public function getTotalMinutesGrade3Attribute()
    {
       return $this->timeRecords()->where('grade_id', '=', 1)->sum('minutes');
    }

    /**
     * Get total minutes for grade 4
     *
     * @return minutes total
     */
    public function getTotalMinutesGrade4Attribute()
    {
       return $this->timeRecords()->where('grade_id', '=', 2)->sum('minutes');
    }

    /**
     * Get total minutes for grade 5
     *
     * @return minutes total
     */
    public function getTotalMinutesGrade5Attribute()
    {
       return $this->timeRecords()->where('grade_id', '=', 3)->sum('minutes');
    }

    /**
     * Get total minutes for timesheet 
     *
     * @return minutes total
     */
    public function getTotalMinutesAttribute()
    {
       return $this->timeRecords()->sum('minutes');
    }

}

app/Http/Controllers/TimeSheetController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\TimeSheet;
use App\TimeRecord;
use App\CostCenter;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;
use PDF;
use File;
use ZipArchive;

class TimeSheetController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $emptySearch = 1;
        $queryOrder = "CASE WHEN month = 'January' THEN 1";
        $queryOrder .= " WHEN month = 'February' THEN 2";
        $queryOrder .= " WHEN month = 'March' THEN 3";
        $queryOrder .= " WHEN month = 'April' THEN 4";
        $queryOrder .= " WHEN month = 'May' THEN 5";
        $queryOrder .= " WHEN month = 'June' THEN 6";
        $queryOrder .= " WHEN month = 'July' THEN 7";
        $queryOrder .= " WHEN month = 'August' THEN 8";
        $queryOrder .= " WHEN month = 'September' THEN 9";
        $queryOrder .= " WHEN month = 'October' THEN 10";
        $queryOrder .= " WHEN month = 'November' THEN 11";
        $queryOrder .= " ELSE 12 END";
        $timeSheets = TimeSheet::where('user_id', Auth::user()->id)->orderByRaw($queryOrder)->get();

        if($request->has('q')){
            $q = $request->get( 'q' );
            Log::info('Query Check : ' . $q);
            $timeSheets = TimeSheet::where('name', 'LIKE', '%' . $q . '%')->where('user_id', Auth::user()->id)->orderByRaw($queryOrder)->get();
            if (count( $timeSheets ) == 0) {
                $emptySearch = 0;
            }else{
                $emptySearch = 1;
            }
        }elseif($request->filter == 'all'){
            $timeSheets = TimeSheet::where('user_id', Auth::user()->id)->orderByRaw($queryOrder)->get();
            $emptySearch = 1;
            //$costCenters = CostCenter::all();
        }
        return view('TimeSheet.index', compact('timeSheets', 'emptySearch'));
    }

    public function create()
    {
        $timeSheets = TimeSheet::all();
        return view('TimeSheet.create', compact('timeSheets'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'month' => 'required|string',
            'name' => 'required|string',
            'year' => 'required|integer',
        ]);

        $timesheet = new TimeSheet;
        $timesheet->month = $request->get('month');
        $timesheet->name = $request->get('name');
        $timesheet->year = $request->get('year');
        $timesheet->company = $request->get('company');
        $timesheet->user_id = Auth::user()->id;
        $timesheet->save();
        return redirect('/timeSheet')->with('Created');
    }

    public function show(TimeSheet $timeSheet)
    {
    }

    public function edit(TimeSheet $timeSheet)
    {
        return view('TimeSheet.edit', compact('timeSheet'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\TimeSheet  $timeSheet
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, TimeSheet $timeSheet)
    {
        $request->validate([
            'month' => 'required|string',
            'name' => 'required|string',
            'year' => 'required|integer',
        ]);
        //Update
        $timeSheet->name = is_null($request->name) ? $timeSheet->name : $request->name;
        $timeSheet->month = is_null($request->month) ? $timeSheet->month : $request->month;
        $timeSheet->year = is_null($request->year) ? $timeSheet->year : $request->year;
        $timeSheet->save();
        return redirect('/timeSheet');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\TimeSheet  $timeSheet
     * @return \Illuminate\Http\Response
     */
    public function destroy(TimeSheet $timeSheet)
    {
        $timeSheet->delete();
        return redirect('/timeSheet');
    }


    /**
     * Generates a Zip folder with Timesheet PDFs.
     * 
     * Method that when provided Pdf timesheet id's and or a costCenterId will generate the timesheet PDF and downlaod the PDF(s) in a zip folder.
     * All records related to the ID of the timesheet will be rerieved and sorted in a chronological order in a PDF
     * @param   int	$colnnovateid
     * @param  	int $innovationID
     * @param  	int $ktpid
     * @param  	int $ptlid
     * @param  	int $academyid
     * 
     */
    public function generateTimeSheetsPDFDepricated($costCenterid=null, $innovationID=null, $colnnovateid=null, $ktpid=null, $ptlid=null, $academyid=null)
    {
        //global vars
        $user = Auth::user();
        $costCenter = null;

        //setting pdf structure
        $files = array();
        $rootPath = 'public/' . $user->id . '/multipleTs/';
        $colnnovatePdf = null;
        $ptlPdf = null;
        $ktpPdf = null;
        $innovationPdf = null;
        $academyPdf = null;

        //KTP
        $ktimeSheet = null;
        $kTimeRecords = null;

        //Academy
        $atimeRecords = null;

        //colnnovate & innovate
        $timeRecordsArrayInnovation = array();
        $timeRecordsArrayColnnovate = array();
        $iTitle = "";
        $cTitle = "";

        //ptl
        $ptlTimeSheet = null;
        $ptimeRecords = null;
        $timeRecordArrayPTL = array();
        $days = array("MON"=>[], "TUE"=>[], "WED"=>[], "THU"=>[], "FRI"=>[], "SAT"=>[]);
        //Array of Keys
        $weekMap = [
            0 => 'SUN',
            1 => 'MON',
            2 => 'TUE',
            3 => 'WED',
            4 => 'THU',
            5 => 'FRI',
            6 => 'SAT',
        ];
        
        if($innovationID != null){
            $title = "Innovation Voucher Timesheet";
            $timeSheet = TimeSheet::find($innovationID);
            $decision = "timesheet";
            
            if($costCenterid != null){
                $timeRecordsArray = $this->innovationColnnovate($costCenterid, $innovationID);
            }else{
                $timeRecordsArray = $this->innovationColnnovate($innovationID);
            }
            $file_name = 'innovation-' . Carbon::now()->format('d-m-Y-H-i-s') .'.pdf';
            File::isDirectory($rootPath) or File::makeDirectory($rootPath, 0777, true, true);
            
            $pdf = PDF::loadview('Pdf.timesheet', compact('user', 'timeRecordsArray', 'title', 'costCenter', 'innovationID', 'timeSheet', 'decision'))
            ->setPaper('a4', 'landscape')->save($rootPath . $file_name);
           // $this->downloadPDF($pdf, $file_name);
            array_push($files, $file_name);
        }

        if($colnnovateid != null){
            $title = " HE - FE PROJECT TIMESHEET";
            $timeSheet = TimeSheet::find($colnnovateid);
            $decision = null;
            
            if($costCenterid != null){
                $timeRecordsArray = $this->innovationColnnovate($costCenterid, $colnnovateid);
            }else{
                $timeRecordsArray = $this->innovationColnnovate($colnnovateid);
            }
            $file_name = 'colnnovate-' . Carbon::now()->format('d-m-Y-H-i-s') .'.pdf';
            File::isDirectory($rootPath) or File::makeDirectory($rootPath, 0777, true, true);
            
            $pdf = PDF::loadview('Pdf.timesheet', compact('user', 'costCenter', 'colnnovateid', 'timeRecordsArray', 'title', 'costCenter', 'timeSheet', 'decision'))
            ->setPaper('a4', 'landscape')->save($rootPath . $file_name);
            //$this->downloadPDF($pdf, $file_name);
            array_push($files, $file_name);
        }

        //Academy
        if($academyid != null){
            $aTimeSheet = TimeSheet::find($academyid);
            if($costCenterid != 0 || $costCenterid != null){
                $costCenter = CostCenter::where('id', $costCenterid)->first();
                $atimeRecords = TimeRecord::where('time_sheet_id', $academyid)->where('cost_center_id', $costCenterid)->orderBy('dateOfRecord')->get();  //->groupBy('dateOfRecord);
            }else{
                $atimeRecords = TimeRecord::where('time_sheet_id', $academyid)->orderBy('dateOfRecord')->get();  //->groupBy('dateOfRecord);
            }
            $file_name = 'academy-' . Carbon::now()->format('d-m-Y-H-i-s') .'.pdf';
            File::isDirectory($rootPath) or File::makeDirectory($rootPath, 0777, true, true);
            
            $pdf = PDF::loadview('Pdf.academy', compact('user', 'costCenter', 'academyid',))
            ->setPaper('a4', 'landscape')->save($rootPath . $file_name);
           // $this->downloadPDF($pdf, $file_name);
            array_push($files, $file_name);
        }

        //KTP
        if($ktpid != null){
            $kTimeSheet = TimeSheet::find($ktpid);
            if($costCenterid != 0 || $costCenterid != null){
                $costCenter = CostCenter::where('id', $costCenterid)->first();
                $kTimeRecords = TimeRecord::where('time_sheet_id', $ktpid)->where('cost_center_id', $costCenterid)->orderBy('dateOfRecord')->get();
            }else{
                $kTimeRecords = TimeRecord::where('time_sheet_id', $ktpid)->orderBy('dateOfRecord')->get();
            }
            $file_name = 'ktp-' . Carbon::now()->format('d-m-Y-H-i-s') .'.pdf';
            File::isDirectory($rootPath) or File::makeDirectory($rootPath, 0777, true, true);

            $pdf = PDF::loadview('Pdf.ktp', compact('user', 'costCenter', 'ktpid', 'timeSheet', 'kTimeRecords'))
            ->setPaper('a4', 'portrait')->save($rootPath . $file_name);
            $ptlPdf = $this->downloadPDF($pdf, $file_name);
            //return $ptlPdf;
            array_push($files, $file_name);
        }

        //PTL

resources/views/TimeSheet/create.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	{{-- Declare Page Size --}}
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Create New Timesheet</h1>
        <div>
	{{-- Error Checking --}}
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        <form method="POST" action="{{route('timeSheet.store')}}">
            @csrf
            <div class="form-group">
                <label for="month">Month:</label>
                <select name="month">
                    <option value="January">January</option>
                    <option value="January">Febarury</option>
                    <option value="January">March</option>
                    <option value="January">April</option>
                    <option value="January">May</option>
                    <option value="January">June</option>
                    <option value="January">July</option>
                    <option value="January">August</option>
                    <option value="January">September</option>
                    <option value="January">October</option>
                    <option value="January">November</option>
                    <option value="January">December</option>
                </select>
            </div>
            <div class="form-group">
                <label for="name">name:</label>
                <input type="text" class="form-control" name="name"/>
            </div>
            <div class="form-group">
                <label for="year">Year:</label>
                <input type="number" class="form-control" name="year"/>
            </div>
            <div class="form-group">
                <label for="company">Company:</label>
                <input type="text" class="form-control" name="company"/>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
		{{-- Error Checking --}}
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/TimeSheet/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	{{-- Declare Page Size --}}
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit Existing TimeSheet</h1>
        <div>
	{{-- Error Checking --}}
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        <form method="post" action="{{ route('timeSheet.update', $timeSheet->id)}}">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="month">Month:</label>
                <select name="month">
                    <option value="January">January</option>
                    <option value="January">Febarury</option>
                    <option value="January">March</option>
                    <option value="January">April</option>
                    <option value="January">May</option>
                    <option value="January">June</option>
                    <option value="January">July</option>
                    <option value="January">August</option>
                    <option value="January">September</option>
                    <option value="January">October</option>
                    <option value="January">November</option>
                    <option value="January">December</option>
                </select>
            </div>
            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name" value="{{ $timeSheet->name }}">
            </div>
            <div class="form-group">
                <label for="year">Year:</label>
                <input type="number" class="form-control" name="year" value="{{ $timeSheet->year }}">
            </div>

            <button type="submit" class="btn btn-secondary">Update</button>
        </form>
    
		{{-- Error Checking --}}
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/TimeSheet/index.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	{{-- Declare Page Size --}}
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Timesheets</h1>
        <div>
	{{-- Error Checking --}}
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
    {{-- <select name="pdfFormat">
        <option value="ktp">ktp</option>
        <option value="timesheet">timesheet</option>
    </select> --}}
    {{-- <label>CostCenter ID</label>
    <select id="costCenter" name="costCenter">
        <option value="">Please Select</option>
        @foreach($costCenters as $costCenter)
            <option value="{{ $costCenter->id }}">{{ $costCenter->number }}</option>
        @endforeach
    </select> --}}




    {{-- template stored as numbers access this, query string sent over --}}
     {{-- @php
         
        // if(isset($_POST['costCenterId'])) {
        //     $ccSelected = $_POST['costCenterId'];
        // }else{
        //     $ccSelected = 0;
        // }
    @endphp --}}

    @if($emptySearch == 0)
            <h2>No Search Results</h2>
    @endif
    <div>
        <form class="form-inline" action="/search" method="POST" role="search" >
            {{ csrf_field() }}
            <div class="input-group">
                <input type="text" name="q" width="500px"
                    placeholder="Search Timesheets by Name"> <span class="input-group-btn">&nbsp;&nbsp;&nbsp;
                    <button type="submit" class="btn btn-primary">Search</button>
                </span>
            </div>
        </form>
        <a style="margin:19px;" href="{{route('timeSheet.create')}}" class="btn btn-primary">New Time Sheet</a>
        <a style="margin:19px;" href="{{route('timeSheet.index', ['filter'=> 'all'])}}" class="btn btn-primary">Show All</a>
    </div>
        <table>
            <thead>
                <tr>
                    <th>Name&nbsp;&nbsp;</th>
                    <th>Month&nbsp;&nbsp;</th>
                    <th>Year&nbsp;&nbsp;</th>
                    <th>Total Hours</th>
                    <th>Total Hours Grade 3</th>
                    <th>Total Hours Grade 4</th>
                    <th>Total Hours Grade 5</th>
                </tr>
            </thead>
            @php
                $costCenterid = 1;
                // $pdfArr = array("colnnovate"=>true, "ktp"=>true, "academy"=>false, "ptl"=>true, "innovation"=>false);
            @endphp
            <tbody>
                @foreach ($timeSheets as $timeSheet)
                    <tr>
                        <td>{{ $timeSheet->name }}&nbsp;&nbsp;</td>
                        <td>{{ $timeSheet->month }}&nbsp;&nbsp;</td>
                        <td>{{ $timeSheet->year  }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                        <td>{{ $timeSheet->total_minutes/60  }}</td>
                        <td>{{ $timeSheet->total_minutes_grade_3/60  }}</td>
                        <td>{{ $timeSheet->total_minutes_grade_4/60  }}</td>
                        <td>{{ $timeSheet->total_minutes_grade_5/60  }}</td>
                        <td></td> 
                        <td><a href="{{route('timeRecords.index', ['id'=>$timeSheet->id])}}" class="btn btn-primary">Show Records</a></td>
                        
                        <td><a href="{{ route('timeSheet.generateTimeSheetsTestPDF') }}?id=1&costcenter=1&colnnovate=true&ktp=true&ptl=true&academy=false&innovation=false" class="btn btn-primary" > Download 3 TimeSheets CC</a></td>
                        <td><a href="{{ route('timeSheet.generateTimeSheetsTestPDF') }}?id=1&colnnovate=false&ktp=true&ptl=true&academy=false&innovation=false" class="btn btn-primary" > Download 2 TimeSheets</a></td>
                        <td><a href="{{ route('timeSheet.generateTimeSheetsTestPDF') }}?id=1&costcenter=1&colnnovate=true&ktp=true&ptl=true&academy=true&innovation=true" class="btn btn-primary" > Download All TimeSheets CC</a></td>
                        <td><a href="{{ route('timeSheet.generateTimeSheetsTestPDF') }}?id=1&colnnovate=true&ktp=true&ptl=true&academy=true&innovation=true" class="btn btn-primary" > Download All TimeSheets</a></td>

                        <td><a href="{{ route('timeSheet.generateColnnovatePDF', ['id'=>$timeSheet->id, 'costCenterid'=>$costCenterid] )  }}" class="btn btn-primary" > Download Colnnovate CC</a></td>
                        <td><a href="{{ route('timeSheet.generateAcademyPDF', ['id'=>$timeSheet->id,'costCenterid'=>$costCenterid]) }}" class="btn btn-primary" > Download Academy CC</a></td>
                        <td><a href="{{ route('timeSheet.generateTimeSheetPDF', ['id'=>$timeSheet->id,'costCenterid'=>$costCenterid]) }}" class="btn btn-primary" > Download Innovation CC</a></td>
                        <td><a href="{{ route('timeSheet.generateKtpPDF', ['id'=>$timeSheet->id,'costCenterid'=>$costCenterid]) }}" class="btn btn-primary" > Download KTP CC</a></td>
                        <td><a href="{{ route('timeSheet.generatePTLPDF', $timeSheet->id) }}" class="btn btn-primary" > Download PTL</a></td>
                        
                        <td><a href="{{ route('timeSheet.generateColnnovatePDF', $timeSheet->id) }}" class="btn btn-primary" > Download Colnnovate</a></td>
                        <td><a href="{{ route('timeSheet.generateAcademyPDF', $timeSheet->id) }}" class="btn btn-primary" > Download Academy</a></td> 
                        <td><a href="{{ route('timeSheet.generateKtpPDF', $timeSheet->id) }}" class="btn btn-primary" > Download KTP</a></td>
                        <td><a href="{{ route('timeSheet.generateTimeSheetPDF', $timeSheet->id) }}" class="btn btn-primary" > Download Innovation</a></td>
                        <td><a href="{{route('timeSheet.edit', $timeSheet->id)}}" class="btn btn-primary">Edit</a></td>
                        <td><form action="{{route('timeSheet.destroy', $timeSheet->id)}}" method="POST">
                        @csrf 
                        @method('DELETE')
                        <button class="btn btn-primary" type="sumbit"> Delete</button></form></td>
                    </tr> 
                @endforeach
            </tbody>
        </table>

		{{-- Error Checking --}}
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection