routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function () {
    Route::resource('account', 'AccountController');
    Route::resource('costCenter', 'CostCenterController');
    Route::resource('courseCode', 'CourseCodeController');
    Route::resource('timeSheet', 'TimeSheetController');
    Route::resource('timeRecords', 'TimeRecordController');
    Route::post('/search', 'TimeSheetController@index')->name('search');
});

Route::get('/timeSheet/downloadts/{costCenterid?}/{innovationID?}/{colnnovateid?}/{ktpid?}/{academyid?}/{ptlid?}', 'TimeSheetController@generateTimeSheetsPDF')->name('timeSheet.generateTimeSheetsPDF');
Route::get('/timeSheet/{id}/downloadtimesheet/{costCenterid?}', 'TimeSheetController@generateTimeSheetPDF')->name('timeSheet.generateTimeSheetPDF');
Route::get('/timeSheet/{id}/downloadktp/{costCenterid?}', 'TimeSheetController@generateKtpCCPDF')->name('timeSheet.generateKtpPDF');
Route::get('/timeSheet/{id}/downloadacademy/{costCenterid?}', 'TimeSheetController@generateAcademyPDF')->name('timeSheet.generateAcademyPDF');
Route::get('/timeSheet/{id}/downloadcolnnovate/{costCenterid?}', 'TimeSheetController@generateColnnovatePDF')->name('timeSheet.generateColnnovatePDF');

Route::get('/timeSheet/{id}/downloadptl', 'TimeSheetController@generatePTLPDF')->name('timeSheet.generatePTLPDF');

Route::get('/tests', 'TimeSheetController@andrew')->name('timeSheet.andrew');
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/pdfdwl', 'TimeSheetController@generateTimeSheetsTestPDF')->name('timeSheet.generateTimeSheetsTestPDF');

Route::get('/test', 'VisitsController@getVisitsByMonth')->name('visits.test');

app/TimeRecord.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Carbon;

class TimeRecord extends Model
{
    public function timeSheet() {
        return $this->belongsTo('App\TimeSheet');
    }
    public function user() {
        return $this->belongsTo('App\User');
    }
    public function grade() {
        return $this->belongsTo('App\Grade');
    }
    public function costCenter() {
        return $this->belongsTo('App\CostCenter');
    }
    
    
    public function scopeMonthTimeRecord($query, $timeSheetId){
        Log::info('auth user' . Auth::user()->id);
        Log::info('ID Parameter' . $timeSheetId);
        $timeRecords = TimeRecord::where('user_id', Auth::user()->id)->where('time_sheet_id', $timeSheetId)->get();
        return $timeRecords;
    }

    /**
     * This will return the differnece in minutes between 2 dateTimes  .
     * 
     * @param  timestamp	$timeIn
     * @param  timestamp	$timeOut
     * @return $timeRecords
     */
    public function scopeGetHoursWorked($query, $timeIn, $timeOut){
        Log::info('time in ' . $timeIn);
        Log::info('time out' . $timeOut);
        $totalMinutes = $timeIn->diffInMinutes($timeOut);
        Log::info('totalMinutes ' . $totalMinutes);
        return $totalMinutes;
    }

    /**
     * This will return the differnece in minutes between 2 dateTimes  .
     * 
     * @return $hoursWorked
     */
    public function getHoursWorkedAttribute()
    {
       return $this->timeIn->diffInMinutes($this->timeOut)/60;
    }


    /**
     * This will return the differnece in minutes between 2 dateTimes  .
     * 
     * @param  timestamp	$timeIn
     * @param  timestamp	$timeOut
     * @return [] $val
     */

    public static function hoursWorked($timeIn, $timeOut)
    {
        $newTimeOut = new Carbon\Carbon($timeOut);
        $newTimeIn = new Carbon\Carbon($timeIn);
        $val = $newTimeIn->diffInHours($newTimeOut);
        return $val;
    }

    protected $fillable = [
        'dateOfRecord', 'time_sheet_id', 'cost_center_id', 'description', 'grade_id', 'user_id', 'timeIn', 'timeOut', 'break', 'minutes', 'dateOfRecord', 'subject'
    ];
}

app/Http/Controllers/TimeRecordController.php
<?php

namespace App\Http\Controllers;

use App\TimeRecord;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use App\CostCenter;
use Carbon\Carbon;
use App\Grade;
use App\TimeSheet;

class TimeRecordController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        Log::info('get id ' . $request->get('id'));
        $currentUser = Auth::user();
        $timeRecords = TimeRecord::monthTimeRecord($request->get('id'));
        $timeSheet = TimeSheet::find($request->get('id'));
        Log::info('timeRecords' . $timeRecords);
        return view('TimeRecord.timeRecordIndex', compact('timeRecords', 'timeSheet'));
    }

    /**
     * Show the form for creating a new resource.
     * 
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $grades = Grade::all();
        Log::info('get id ' . $request->get('id'));
        $costCenters = CostCenter::all();
        $timeRecords = TimeRecord::all();
        $timeSheetID = $request->get('id');
        $grades = Grade::all();
        return view('TimeRecord.createTimeRecord', compact('costCenters', 'timeRecords', 'timeSheetID', 'grades'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'description' => 'required|string',
            'timeIn' => 'required',
            'timeOut' => 'required',
            'costCenter' => 'required',
        ]);

        $timeIn= Carbon::createFromFormat('Y-m-d\TH:i',$request->get('timeIn'));
        $timeOut= Carbon::createFromFormat('Y-m-d\TH:i',$request->get('timeOut'));
        Log::info('total Minutes' . $timeIn);
        Log::info('total Minutes' . $timeOut);
        
       $minutes = TimeRecord::getHoursWorked($timeIn, $timeOut);
       Log::info('Min' . $minutes);
       
        Log::info('break' . $request->get('break'));
        if($request->get('break') == 'on'){
            $break = true;
        }else{
            $break = false;
        }

        $grade = Grade::firstOrNew([
            'type' => $request->get('grade')
        ]);
        $grade->save();


        $timeRecord = new TimeRecord;
        $timeRecord->time_sheet_id = $request->get('timeSheetID');
        $timeRecord->cost_center_id = $request->get('costCenter');
        $timeRecord->description = $request->get('description');
        $timeRecord->timeOut = $request->get('timeOut');
        $timeRecord->timeIn = $request->get('timeIn');
        $timeRecord->break = $break;
        $timeRecord->grade_id = $grade->id;
        $timeRecord->minutes = $minutes;
        $timeRecord->dateOfRecord = $request->get('timeIn');
        $timeRecord->subject = $request->get('subject');
        $timeRecord->user_id = Auth::user()->id;

        $timeRecord->save();
        return redirect('/timeSheet');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\TimeSheet  $timeSheet
     * @return \Illuminate\Http\Response
     */
    public function show(TimeRecord $timeRecord)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\TimeSheet  $timeSheet
     * @return \Illuminate\Http\Response
     */
    public function edit(TimeRecord $timeRecord)
    {
        $grades = Grade::all();
        Log::info('timeIN' . $timeRecord->timeIn);
        $costCenters = CostCenter::all();
        return view('TimeRecord.editTimeRecord', compact('timeRecord', 'costCenters', 'grades'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\TimeSheet  $timeSheet
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, TimeRecord $timeRecord)
    {
        $request->validate([
            'description' => 'required|string',
        ]);
        if($request->get('timeOut') != null && $request->get('timeOut') != null){
            $timeIn= Carbon::createFromFormat('Y-m-d\TH:i',$request->get('timeIn'));
            Log::info('time in' . $timeIn);
            $timeOut= Carbon::createFromFormat('Y-m-d\TH:i',$request->get('timeOut'));
            $minutes = TimeRecord::hours_worked($timeIn, $timeOut);
            Log::info('Min' . $minutes);
        }
        
        $timeRecord->cost_center_id = is_null($request->cost_center_id) ? $timeRecord->cost_center_id : $request->cost_center_id;
        $timeRecord->description = is_null($request->description) ? $timeRecord->description : $request->description;
        $timeRecord->timeIn = is_null($request->timeIn) ? $timeRecord->timeIn : $request->timeIn;
        $timeRecord->timeOut = is_null($request->timeOut) ? $timeRecord->timeOut : $request->timeOut;
        $timeRecord->grade_id = is_null($request->grade_id) ? $timeRecord->grade_id : $request->grade_id;
        $timeRecord->minutes = is_null($request->minutes) ? $timeRecord->minutes : $request->minutes;
        
        
        $timeRecord->save();
        
        if($request->get('break') == 'on'){
            $timeRecord->break = true;
        }else{
            $timeRecord->break = false;
        }
        $timeRecord->save();
        return redirect('/timeSheet');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\TimeSheet  $timeSheet
     * @return \Illuminate\Http\Response
     */
    public function destroy(TimeRecord $timeRecord)
    {
        $timeRecord->delete();
        return redirect('/timeSheet');
    }
}

resources/views/TimeRecord/createTimeRecord.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	{{-- Declare Page Size --}}
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Create New Record</h1>
        <div>
	{{-- Error Checking --}}
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        <form method="POST" action="{{route('timeRecords.store')}}">
            @csrf
        <input type="hidden" class="form-control" name="timeSheetID" value="{{ $timeSheetID }}"/>
            <div class="form-group">
                <label for="description">Description:</label>
                <input type="text" class="form-control" name="description"/>
            </div>
            <div class="form-group">
                <label for="subject">Subject:</label>
                <input type="text" name="subject"/>
            </div>

            <div class="form-group">
                <label for="costCenter">Cost Center:</label>
                <select name="costCenter">
                    @foreach ($costCenters as $costCenter)
                        <option value="{{$costCenter->id}}">{{$costCenter->type}} &nbsp;&nbsp;&nbsp;{{$costCenter->number}}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="grade">Grade:</label>
                <select name="grade">
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                </select>
            </div>

            <div class="form-group">
                <label for="timeIn">Time In:</label>
                <input type="datetime-local" class="form-control" name="timeIn"/>
            </div>

            <div class="form-group">
                <label for="timeOut">Time Out:</label>
                <input type="datetime-local" class="form-control" name="timeOut"/>
            </div>

            <div class="form-group">
                <label for="break">Break:</label>
                <input type="checkbox" name="break"/>
            </div>

            <label for="hoursWorked"></label> {{-- JavaScript Here --}}

            <button type="submit" class="btn btn-primary">Create</button>
        </form>

		{{-- Error Checking --}}
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/TimeRecord/editTimeRecord.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	{{-- Declare Page Size --}}
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit Existing TimeSheet</h1>
        <div>
	{{-- Error Checking --}}
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        <form method="post" action="{{ route('timeRecords.update', $timeRecord->id)}}">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="costCenter">Cost Center:</label>
                <select name="costCenter">
                    @foreach ($costCenters as $costCenter)
                        <option value="{{$costCenter->id}}">{{$costCenter->type}} &nbsp;&nbsp;&nbsp;{{$costCenter->number}}</option>
                    @endforeach
                </select>
            </div>
            
            <div class="form-group">
                <label for="grade">Grade:</label>
                <select name="grade">
                    @foreach ($grades as $grade)
                        <option value="{{$grade->id}}">{{$grade->type}}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="timeIn">Time In:</label>
                <label>{{ $timeRecord->timeIn }}</label>
                <input type="datetime-local" class="form-control" name="timeIn" value="{{ $timeRecord->timeIn }}">
            </div>

            <div class="form-group">
                <label for="timeOut">Time Out:</label>
                <label>{{ $timeRecord->timeOut }}</label>
                <input type="datetime-local" class="form-control" name="timeOut" value="{{ $timeRecord->timeOut }}">
            </div>
            <div class="form-group">
                <label for="description">Description:</label>
                <input type="text" class="form-control" name="description" value="{{ $timeRecord->description }}">
            </div>
            <div class="form-group">
                <label for="break">Break:</label>
                <input type="checkbox" name="checkbox" value="{{ $timeRecord->break }}">
            </div>
            <button type="submit" class="btn btn-secondary">Update</button>
        </form>
    
		{{-- Error Checking --}}
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/TimeRecord/timeRecordIndex.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	{{-- Declare Page Size --}}
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Records for {{ $timeSheet->name }}</h1>
        <div>
	{{-- Error Checking --}}
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        <div><a style="margin:19px;" href="{{route('timeRecords.create', ['id'=>$timeSheet->id])}}" class="btn btn-primary">New Record</a></div>
        <table><thead><tr>
            <th>Month</th>
            <th>&nbsp;&nbsp;Description</th>
            <th>&nbsp;&nbsp;timeIn</th>
            <th>&nbsp;&nbsp;timeOut</th>
            <th>&nbsp;&nbsp;Break</th>
            <th>&nbsp;Hours</th>
            <th>&nbsp;Grade</th>
            <th>&nbsp;Project Code</th>
        </tr></thead><tbody>
        @foreach($timeRecords as $timeRecord)
            <tr>
                <td>&nbsp;&nbsp;{{$timeSheet->month}}</td>
                <td>&nbsp;&nbsp;{{$timeRecord->description}}</td>
                <td>&nbsp;&nbsp;{{$timeRecord->timeIn}}</td>
                <td>&nbsp;&nbsp;{{$timeRecord->timeOut}}</td>
                @if($timeRecord->break == 1)
                    <td>Yes</td>
                @else
                    <td>No</td>
                @endif
                <td>&nbsp;&nbsp;{{$timeRecord->minutes/60}}</td>
                <td>&nbsp;&nbsp;{{$timeRecord->grade->type}}</td>
                <td>&nbsp;{{$timeRecord->costCenter->number}}</td>
                <td>&nbsp;&nbsp;<a href="{{route('timeRecords.edit', $timeRecord->id)}}" class="btn btn-primary">Edit</a></td>
                <td><form action="{{route('timeRecords.destroy', $timeRecord->id)}}" method="POST">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger" type="submit"> Delete</button></form></td>
            </tr>
        @endforeach</tbody>
        </table>
		{{-- Error Checking --}}
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection